from enum import Enum


class NBATeam(Enum):
    ATL = "Hawks"
    BOS = "Celtics"
    BRK = "Nets"
    CHO = "Hornets"
    CHI = "Bulls"
    CLE = "Cavaliers"
    DAL = "Mavericks"
    DEN = "Nuggets"
    DET = "Pistons"
    GSW = "Warriors"
    HOU = "Rockets"
    IND = "Pacers"
    LAC = "Clippers"
    LAL = "Lakers"
    MEM = "Grizzlies"
    MIA = "Heat"
    MIL = "Bucks"
    MIN = "Timberwolves"
    NOP = "Pelicans"
    NYK = "Knicks"
    OKC = "Thunder"
    ORL = "Magic"
    PHI = "76ers"
    PHO = "Suns"
    POR = "Blazers"  # This has to be Blazers because we're just looking at the last word to match
    SAC = "Kings"
    SAS = "Spurs"
    TOR = "Raptors"
    UTA = "Jazz"
    WAS = "Wizards"
